#!/bin/sh
# Updates weather forecast

FILE="$HOME/.weatherreport.tmp"
FILER="$HOME/.weatherreport"

curl -s --max-time 10 "wttr.in/$location" > $FILE 

if [ -s "$FILE" ]
then
    mv $FILE $FILER
else
    rm $FILE 
fi
