#!/bin/bash
choices="Off\nCycle"

chosen=$(echo -e "$choices" | dmenu -i)

mouse=$(sudo ratbagctl list | awk '{print $1}' | sed 's/://')

case "$chosen" in
	Off) sudo ratbagctl $mouse led 0 set mode off ;;
	Cycle) sudo ratbagctl $mouse led 0 set mode cycle && sudo ratbagctl $mouse led 0 set duration 25000 ;;
esac
